# Documentation available at https://pwa.spomky-labs.com/
## Please add the favicons, manifest or serviceworker sections depending on your needs.
pwa:
    image_processor: 'pwa.image_processor.gd'

    serviceworker:
        enabled: true
        skip_waiting: true
        src: 'assets/sw.js' # Указываем путь к ВАШЕМУ файлу
        workbox:
            enabled: true
        
    
    manifest:
        enabled: true
        name: 'Simple Chat'
        short_name: 'SymfonyPWA'
        description: 'Symfony-8 Simple Chat'
        background_color: '#ffffff'
        theme_color: '#4f46e5'
        display: 'standalone'
        scope: '/'
        start_url: '/'
        icons:
            - src: '%kernel.project_dir%/assets/images/logo.png' 
              sizes: [192, 512] 
        
        screenshots:
            # Скриншот для мобильных
            - src: 'images/mobile.png'
              width: 750
              height: 1334
              format: 'image/png'
              label: 'Mobile version'

            # Скриншот для десктопа
            - src: 'images/desktop.png'
              width: 1280
              height: 598
              format: 'image/png'
              form_factor: 'wide'
              label: 'Desktop version'

