# Documentation available at https://pwa.spomky-labs.com/
## Please add the favicons, manifest or serviceworker sections depending on your needs.
pwa:
    image_processor: 'pwa.image_processor.gd'
    
    manifest:
        enabled: true
        name: 'Simple Chat'
        short_name: 'SymfonyPWA'
        description: 'Symfony8 Simple Chat'
        background_color: '#ffffff'
        theme_color: '#4f46e5'
        display: 'standalone'
        scope: '/'
        start_url: '/'
        icons:
            - src: '%kernel.project_dir%/assets/images/logo.png' 
              sizes: [192, 512] 

    serviceworker:
        enabled: true
        workbox:
            enabled: true
